export { default as HomeHero } from './HomeHero';
export { default as HomeHero2 } from './HomeHero2';
export { default as HomeHeroMap } from './HomeHeroMap';
export { default as HomeAboutMontessoriConnect } from './HomeAboutMontessoriConnect';
export { default as HomeResources } from './HomeResources';
export { default as HomeBecomeMemeber } from './HomeBecomeMemeber';
export { default as HomeMCInstagram } from './HomeMCInstagram';
export { default as HomeSubscribe } from './HomeSubscribe';
export { default as HomePlatformStatistics } from './HomePlatformStatistics';
export { default as HomeDarkMode } from './HomeDarkMode';
// export { default as HomeVectorMap } from './HomeVectorMap';
// export { default as HomeLookingFor } from './HomeLookingFor';
// export { default as HomeColorPresets } from './HomeColorPresets';
// export { default as HomePricingPlans } from './HomePricingPlans';
export { default as HomeAdvertisement } from './HomeAdvertisement';
// export { default as HomeCleanInterfaces } from './HomeCleanInterfaces';
// export { default as HomeHugePackElements } from './HomeHugePackElements';
export { default as HomeWorldMap } from './HomeWorldMap';
export { default as HomeUserRoles } from './HomeUserRoles';
export { default as HomeUserRoles2 } from './HomeUserRoles2';

export { default as HomeFaq } from './HomeFaq';
export { default as HomeEvents } from './HomeEvents';
